#!/usr/bin/env bash

[[ -f /etc/ah-client.conf ]] && . /etc/ah-client.conf

[[ -z "$AH_BUCKET" || -z "$AH_APP" || -z "$AH_ENV" ]] \
  && echo "missing environment configuration" 1>&2 && exit 1

appdir=/opt/$AH_APP
appgit=s3://$AH_BUCKET/repo/$AH_APP
appenv=s3://$AH_BUCKET/data/$AH_APP/${AH_ENV}.env
appidx=s3://$AH_BUCKET/data/$AH_APP/${AH_ENV}.grants
appsha=s3://$AH_BUCKET/data/$AH_APP/${AH_ENV}.sh
s3cret=s3://$AH_BUCKET/secrets

if [[ -z "$AH_MASTER_REGION" ]]; then
  export AH_MASTER_REGION=us-east-1
fi

usage() {
  local prog=$(basename ${BASH_SOURCE[0]})
  exec 1>&2
  [[ $1 ]] && echo "$prog: $1" && echo
  cat <<EOT
USAGE: $prog [-hc]
       $prog TARGET ...

Where TARGET arguments are make(1) targets in the ah(1) project Makefile.

OPTIONS:
  -h          Print this usage info and exit.
  -c          Print environment configuration variables and exit.
  -u          Update environment configuration variables and exit.
  -s SHA      Set the AH_SHA to deploy.
EOT
  exit 1;
}

info() { echo -e "\033[1m$1\033[0m" 1>&2; }
warn() { echo -e "\033[33m$1\033[0m" 1>&2; }

update_vars() {
  local idx
  info "Fetching env vars..."
  mkdir -p .ah
  idx=$(AWS_DEFAULT_REGION=$AH_MASTER_REGION aws s3 cp $appidx - || echo 0)
  if [[ "$idx" != 0 ]]; then
    for i in $idx; do
      echo "${i}=$(AWS_DEFAULT_REGION=$AH_MASTER_REGION aws s3 cp ${s3cret}/$i - 2>/dev/null)"
    done > .ah/ah.env
  else
    AWS_DEFAULT_REGION=$AH_MASTER_REGION aws s3 ls ${s3cret}/ \
      |awk '{print $NF}' \
      | while read key; do
        val=$(AWS_DEFAULT_REGION=$AH_MASTER_REGION aws s3 cp ${s3cret}/$key - 2>/dev/null) || continue ; \
        echo "${key##*/}=$val" ; \
      done > .ah/ah.env
  fi
  AWS_DEFAULT_REGION=$AH_MASTER_REGION aws s3 cp $appenv - 2>/dev/null >> .ah/ah.env
}

while getopts hcus: o; do
  case $o in
    c) set |grep ^AH_ ; cat $appdir/.ah/ah.env 2>/dev/null ; exit 0 ;;
    u) cd $appdir && update_vars ; exit 0 ;;
    s) DEPLOY_SHA="$OPTARG" ;;
    *) usage ;;
  esac
done
shift $((OPTIND-1))

[[ -z "$1" ]] && usage

info "Updating env version..."

if [[ -z "$DEPLOY_SHA" ]]; then
    # this file exports the AH_SHA definition set by 'ah putsha'
    . <(AWS_DEFAULT_REGION=$AH_MASTER_REGION aws s3 cp $appsha -)
else
    # export the supplied DEPLOY_SHA
    export AH_SHA="$DEPLOY_SHA"
fi

appsrc=$(mktemp -d -p /opt ${AH_APP}.${AH_SHA}.XXX)
apptgz=s3://$AH_BUCKET/repo/$AH_APP/${AH_SHA}.tar.gz
apptgt=s3://$AH_BUCKET/data/$AH_APP/${AH_SHA}.tar.gz

pushd $appsrc
  info "Fetching repo..."
  AWS_DEFAULT_REGION=$AH_MASTER_REGION aws s3 cp $apptgz - |tar xzf -

  info "Updating environment variables..."
  update_vars
  eval "$(cat .ah/ah.env |sed 's@^@export @')"
popd > /dev/null

appdir_old=$(readlink -e $appdir)

info "Linking $appsrc -> $appdir..."
ln -sfn $appsrc $appdir

info "Running make..."
make -C $appdir "$@"

info "Cleaning up..."
[[ -d "$appdir_old" ]] && rm -rf $appdir_old

info "Done."
