.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "AH" "1" "November 2017" "" "AH MANUAL"
.
.SH "NAME"
\fBah\fR \- simple, service oriented management of AWS resources
.
.SH "SYNOPSIS"
\fBah\fR \fIcommand\fR [\fIOPTIONS\fR\.\.\.]
.
.SH "DESCRIPTION"
\fBAh\fR is a tool for managing the infrastructure resources associated with services hosted on Amazon Web Services (AWS)\.
.
.SH "COMMANDS"
Commands are organized by scope: global, application, and environment\.
.
.SS "Global Commands"
These commands are not specific to any application\. They may be executed from any directory\.
.
.TP
\fBorgs\fR
Print a listing of existing org names\.
.
.TP
\fBgetorg\fR \fIorg\fR
Print the config settings associated with \fIorg\fR\.
.
.TP
\fBputorg\fR \fIorg\fR
Create or update the org named \fIorg\fR, starting with a copy of \fItemplate\fR if provided\. Input may be provided interactively from the terminal or via \fIstdin\fR\. See \fBFIlES\fR below for a description of the expected format\.
.
.TP
\fBrmorg\fR \fIorg\fR
Deletes the org named \fIorg\fR\.
.
.TP
\fBupgrade\fR
Update static \fBah\fR bootstrapping files on S3\. Needed when \fBah\fR itself is updated to a new version\.
.
.TP
\fBputsecret\fR \fIsecret\fR
Create or update the S3 secret file for the variable \fIsecret\fR\. The value is read from \fIstdin\fR\. \fBNOTE: the value must be explicitly quoted if it contains spaces, newlines, etc\.\fR
.
.TP
\fBrmsecret\fR \fIsecret\fR
Delete the S3 secret file for the variable \fIsecret\fR\.
.
.TP
\fBgrants\fR [\fB\-u\fR]
Print the table of S3 secret variable and \fBah\fR environment names for all environments that have been granted access to S3 secret variable files\. The \fB\-u\fR option updates the grants index for the current environment (should not be necessary unless the index has somehow gotten out of sync with the secrets granted)\.
.
.SS "Application Commands"
These commands operate at the application level and must be executed from an application git directory\. The \fBinit\fR command must be executed to initialize the application before any other application or environment scope commands are attempted\.
.
.TP
\fBinit\fR
Configure a new application and create associated AWS resources\. Input may be provided interactively from the terminal or via \fIstdin\fR\. See \fBFILES\fR below for a description of the expected format\.
.
.TP
\fBregion\fR [\fIregion\fR]
Set the default AWS region to \fIregion\fR if \fIregion\fR is specified, or print the current default region name\.
.
.TP
\fBpush\fR
Push the \fBHEAD\fR of the current application git repo and the contents of the target directory to S3\.
.
.TP
\fBshas\fR
Print the list of SHAs that have been uploaded via the \fBpush\fR command for the current application\.
.
.TP
\fBenvs\fR [\fB\-a\fR]
Print the list of environments associated with the current application\. If the \fB\-a\fR option is provided print the table of \fBah\fR application and environment names for all environments\.
.
.TP
\fBstatus\fR
Print status info for instances associated with this application\.
.
.SS "Environment Commands"
These commands operate at the environment level and must be executed from the application git directory\. The \fBenv\fR command must be used to set the current environment before any other environment scope commands are attempted\.
.
.TP
\fBenv\fR [\fIenv\fR]
Set the default environment to \fIenv\fR if \fIenv\fR is specified, or print the current environment name\.
.
.TP
\fBputvars\fR
Update the current environment\'s application config variables, read from \fIstdin\fR\. See \fBFILES\fR below for a description of the expected format\.
.
.TP
\fBgetvars\fR
Print the application config variables stored for the current environment by the last \fBputvar\fR\.
.
.TP
\fBputsha\fR [\fIrev\fR]
Set the configured deploy SHA for the current environment to the SHA associated with git revision \fIrev\fR (or \fBHEAD\fR if not provided)\. See the \fBSPECIFYING REVISIONS\fR section of the \fBgit\-rev\-parse\fR(1) manual for details\.
.
.TP
\fBgetsha\fR
Print the currently configured deploy SHA for the current environment\.
.
.TP
\fBlaunch\fR
Interactive command to create AWS resources for a new environment\.
.
.TP
\fBterminate\fR
Destroy all AWS resources associated with the current environment\. Only resources managed by \fBah\fR will be affected\.
.
.TP
\fBsecrets\fR [\fB\-a\fR]
Print all S3 secrets to which the current environment has access, or if the \fB\-a\fR option is specified print all secrets to which the current user has access\. See \fBFILES\fR below for a description of the output format\.
.
.TP
\fBgrant\fR \fIsecret\fR
Grant permission for the current environment\'s instances to access the S3 secret file for the variable \fIsecret\fR\.
.
.TP
\fBrevoke\fR \fIsecret\fR
Revoke permission for the current environment\'s instances to access the S3 secret file for the variable \fIsecret\fR\.
.
.SH "ENVIRONMENT"
The following environment variables must be set before using \fBah\fR:
.
.TP
\fBAH_BUCKET\fR
The name of the S3 bucket allocated for use by \fBah\fR\. This bucket must be created before using \fBah\fR\.
.
.SH "CONFIG"
.
.IP "\(bu" 4
\fBah\fR will source \fB$HOME/\.ah/config\fR\. This is used to set ah environment variables and extend the functionality of ah\.
.
.IP "\(bu" 4
A convenience function \fBah_load_extension repo ref\fR is provided\. This will install ah extensions from the specified repo at the specified revision to \fB$HOME/\.ah/extensions\fR\. For example: \fBah_load_extension git@github\.com:yourorg/cool\-ah\-extensions 2\.0\fR
.
.IP "" 0
.
.SH "FILES"
The following configuration files are used to configure the \fBah\fR environment\. The format of these files is one \fINAME\fR=\fIvalue\fR pair per line, suitable for eval by the \fBbash\fR(1) shell\.
.
.TP
\fI$APPDIR\fR\fB/\.ah/ah\.conf\fR
This file contains the application configuration, as set by the \fBinit\fR command\. Settings in this file only apply to this application\. This file \fBmust\fR be committed to the git repository for the application\.
.
.TP
\fI$APPDIR\fR\fB/\.ah/env\fR
This file contains the name of the current default environment, as set by the \fBenv\fR command\.
.
.TP
\fI$APPDIR\fR\fB/\.ah/region\fR
This file contains the name of the current default AWS region, as set by the \fBregion\fR command\.
.
.SH "COPYRIGHT"
Copyright \(co 2017 Adzerk \fB<engineering@adzerk\.com>\fR, distributed under the Eclipse Public License, version 1\.0\. This is free software: you are free to change and redistribute it\. There is NO WARRANTY, to the extent permitted by law\.
.
.SH "SEE ALSO"
\fBah\fR(8), \fBaws\fR(1), \fBgit\fR(1)
