#!/usr/bin/env bash

aws s3api list-objects --bucket adzerk-andhrimnir --prefix secrets/ \
    | jt Contents Key % \
    | while read key; do
        val=$(aws s3 cp s3://$AH_BUCKET/$key - 2>/dev/null) || continue ; \
        echo "${key##*/}=$val" ; \
      done
