#!/usr/bin/env bash

update_index() {
  echo -n "$(ah_info "Updating grants index...")" 1>&2
  ah_update_grants_index
  ah_success "done." 1>&2
}

while getopts u o; do
  case $o in
    u) update_index ;;
    *) ah_die "usage: $AH grants [-u]" ;;
  esac
done
shift $((OPTIND-1))

ah_all_grants
