#!/usr/bin/env bash

[[ $# -lt 1 ]] && ah_die "secret name required"

secret=$1
policy_name="${1}=$(ah_var AH_ENV)"

ah_check "policy does not already exist" ah_not ah_policy_exists "$policy_name" || exit 0

S3_READONLY=$(cat <<EOT
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject"
      ],
      "Resource": [
        "$(ah_s3_arn $(ah_secret $secret))"
      ]
    }
  ]
}
EOT
)

ah_try -m "Creating S3 access policy..." \
  aws iam create-policy \
    --path /ah/secrets/ \
    --policy-name $policy_name \
    --description "Ah instance access to S3 secret." \
    --policy-document "$S3_READONLY" \
    > /dev/null

ah_try -m "Attaching policy to environment role..." \
  aws iam attach-role-policy \
    --role-name $(ah_var AH_ENV) \
    --policy-arn $(ah_policy_arn ah/secrets/$policy_name) \
    > /dev/null

ah_try -m "Updating grants index..." ah_update_grants_index
