#!/usr/bin/env bash

[[ $# -gt 0 ]] || ah_die "secret variable name required"

aws iam list-policies \
  |jt Policies [ Path % ] [ PolicyName % ] \
  |awk '$1 == "/ah/secrets/" {print $2}' \
  |awk -F= "\$1 == \"$1\" {print \$2}"
