#!/usr/bin/env bash

[[ -z "$AH_ENV" ]] && ah_die "environment not configured: do '$AH env <name>'"

aws iam list-policies \
  |jt . [ Path % ] [ PolicyName % ] \
  |awk '$1 == "/ah/secrets/" {print $2}' \
  |awk -F= "\$2 == \"$AH_ENV\" {print \$1}"
