#!/usr/bin/env bash

aws s3api list-objects-v2 --bucket $AH_BUCKET --prefix etc \
  |jt Contents [ Key % ] [ LastModified % ] \
  |sed 's@^etc/@@' \
  |awk -F '	' '$1 ~ /\.conf$/ {print}' \
  |sed 's@\.conf@@' \
  |sort
