#!/usr/bin/env bash

aws s3api list-objects-v2 \
  --bucket $(ah_var AH_BUCKET) \
  --prefix etc \
  --region $AH_MASTER_REGION \
  |jt Contents [ Key % ] [ LastModified % ] \
  |sed 's@^etc/@@' \
  |awk -F '	' '$1 ~ /\.conf$/ {print}' \
  |sed 's@\.conf@@' \
  |sort
