#!/usr/bin/env bash

AH_ORG=$1

[[ -n "$AH_ORG" ]] || ah_die "Usage: $AH putorg <org> [<template>]"
[[ $(echo "$AH_ORG" |wc -w) -gt 1 ]] && ah_die "org name must not contain spaces"

if ! [[ -t 0 ]]; then
  vars=$(cat)
else
  PS3="Use existing Org as a template?"
  select template in "NO TEMPLATE" $(ah_s3_ls etc |sed 's@\.conf$@@'); do
    case "$template" in
      "NO TEMPLATE") break ;;
      *) . <(aws s3 cp s3://$AH_BUCKET/etc/${template}.conf - |grep . |sed 's@^@export @')
        ;;
    esac
  done

  while true; do
    dfl="$AH_DEFAULT_SGS"
    read -p "[AH_DEFAULT_SGS] SGs for default ingress rules (all access)? [${AH_DEFAULT_SGS:-$dfl}] " AH_DEFAULT_SGS
    export AH_DEFAULT_SGS="${AH_DEFAULT_SGS:=$dfl}"

    dfl="$AH_AZS"
    read -p "[AH_AZS] Availability zones in which to launch instances? [${AH_AZS:-$dfl}] " AH_AZS
    export AH_AZS="${AH_AZS:=$dfl}"

    dfl="$AH_BILLING_GROUP"
    read -p "[AH_BILLING_GROUP] Billing group? [${AH_BILLING_GROUP:-$dfl}] " AH_BILLING_GROUP
    export AH_BILLING_GROUP="${AH_BILLING_GROUP:=$dfl}"

    dfl="$AH_BILLING_PROJECT"
    read -p "[AH_BILLING_PROJECT] Billing project? [${AH_BILLING_PROJECT:-$dfl}] " AH_BILLING_PROJECT
    export AH_BILLING_PROJECT="${AH_BILLING_PROJECT:=$dfl}"

    PS3="[AH_MACHINE_IMAGE] Machine image? "
    select AH_MACHINE_IMAGE in $(echo "$IMAGES" |cut -f2 |sort); do
      [[ -n "$AH_MACHINE_IMAGE" ]] && break
    done
    export AH_MACHINE_IMAGE

    PS3="[AH_KEY_PAIR] Key pair? "
    select AH_KEY_PAIR in $(echo "$KEYS" |sort); do
      [[ -n "$AH_KEY_PAIR" ]] && break
    done
    export AH_KEY_PAIR

    dfl="m3.medium"
    read -p "[AH_INSTANCE_TYPE] Instance type? [${AH_INSTANCE_TYPE:-$dfl}] " AH_INSTANCE_TYPE
    export AH_INSTANCE_TYPE="${AH_INSTANCE_TYPE:=$dfl}"

    vars=$(set |grep -E '^AH_(AZS|DEFAULT_SGS|BILLING_GROUP|BILLING_PROJECT|ENV|MACHINE_IMAGE|KEY_PAIR|INSTANCE_TYPE)=')

    echo
    echo "$vars"
    echo

    read -sn 1 -p "Approve? [yN] " approve
    [[ "$approve" == "y" ]] && echo && break;

    echo
    echo "Okay, starting over (ctrl-c to abort)."
    echo
  done

  echo
fi

echo -n "Saving org settings..."
echo "$vars" |aws s3 cp - s3://$AH_BUCKET/etc/${AH_ORG}.conf
echo done.
