#!/usr/bin/env bash

hash=$(git rev-parse HEAD)
s3uri="s3://$(ah_repo "$(ah_var AH_APP)")/${hash}.tar.gz"
tmp1=$(ah_mktemp)
tmp2=$(ah_mktemp)

trap "rm -f $tmp1 $tmp2" EXIT

echo -n "Creating tarball..."
git archive --format tar $hash > $tmp1

if [[ -d "$(ah_var AH_TARGET)" ]]; then
  echo -n "adding ${AH_TARGET}..."
  ah_tar cf $tmp2 "$AH_TARGET"
  ah_tar Af $tmp1 $tmp2
fi
echo done.

echo -n "Pushing repo to S3..."
cat $tmp1 |gzip -9 |aws s3 cp - "$s3uri"
echo done.
