#!/usr/bin/env bash

[[ -z "$AH_APP" ]] && ah_die "application not configured: do '$AH init'"

hash=$(git rev-parse HEAD)
s3uri="s3://$(ah_repo "$(ah_var AH_APP)")/${hash}.tar.gz"
tmp1=$(mktemp)
tmp2=$(mktemp)

trap "rm -f $tmp1 $tmp2" EXIT

echo -n "Pushing repo..."
git archive --format tar $hash > $tmp1

if [[ -d "$(ah_var AH_TARGET)" ]]; then
  echo -n "adding ${AH_TARGET}..."
  tar cf $tmp2 "$AH_TARGET"
  tar Af $tmp1 $tmp2
fi
echo done.

echo -n "Pushing repo to S3..."
cat $tmp1 |gzip -9 |aws s3 cp - "$s3uri"
echo done.
