#! /bin/bash
# vim: set ft=sh:

status=$(aws autoscaling describe-auto-scaling-groups \
  |jt AutoScalingGroups \
    [ Tags [ Key % ] [ Value % ] ] \
    [ AutoScalingGroupName % ] \
    Instances \
      [ InstanceId % ] \
      [ AvailabilityZone % ] \
      [ HealthStatus % ] \
      [ LifecycleState % ] \
  |grep ^AhApplication \
  |awk "\$2 == \"$(ah_var AH_APP)\" {print}" \
  |cut -f3- \
  |sort
)

dns=$(aws ec2 describe-instances --instance-ids $(echo "$status" |cut -f2) \
  |jt Reservations Instances [ InstanceId % ] [ PublicDnsName % ] [ PrivateIpAddress % ])

join -1 1 -2 2 -t '	' <(echo "$dns" |sort) <(echo "$status" |sort -k2) \
  |awk -F '	' '{print $4 "\t" $1 "\t" $5 "\t" $6 "\t" $7 "\t" $2 "\t" $3}'
