#!/usr/bin/env bash

all_secrets() {
  aws s3api list-objects --bucket adzerk-andhrimnir --prefix secrets/ --region $AH_MASTER_REGION \
    | jt Contents Key % \
    | while read key; do
        val=$(aws s3 cp s3://$(ah_var AH_BUCKET)/$key - --region $AH_MASTER_REGION 2>/dev/null) || continue
        echo "${key##*/}=$val"
      done
}

while getopts a o; do
  case $o in
    a) all_secrets ; exit 0 ;;
    *) ah_die "usage: $AH secrets [-a]" ;;
  esac
done
shift $((OPTIND-1))

aws iam list-policies \
  | jt . [ Path % ] [ PolicyName % ] \
  | awk '$1 == "/ah/secrets/" {print $2}' \
  | awk -F= "\$2 == \"$(ah_var AH_ENV)\" {print \$1}" \
  | while read key; do
      val=$(aws s3 cp s3://$(ah_var AH_BUCKET)/secrets/$key - --region $AH_MASTER_REGION 2>/dev/null) || continue
      echo "${key}=$val"
    done
