#!/usr/bin/env bash

all_secrets() {
  aws s3api list-objects --bucket adzerk-andhrimnir --prefix secrets/ \
      | jt Contents Key % \
      | while read key; do
          val=$(aws s3 cp s3://$AH_BUCKET/$key - 2>/dev/null) || continue
          echo "${key##*/}=$val"
        done
}

while getopts a o; do
  case $o in
    a) all_secrets ; exit 0 ;;
    *) ah_die "usage: $AH secrets [-a]" ;;
  esac
done
shift $((OPTIND-1))

[[ -z "$AH_ENV" ]] && ah_die "environment not configured: do '$AH env <name>'"

aws iam list-policies \
  |jt . [ Path % ] [ PolicyName % ] \
  |awk '$1 == "/ah/secrets/" {print $2}' \
  |awk -F= "\$2 == \"$AH_ENV\" {print \$1}" \
  |while read key; do
    val=$(aws s3 cp s3://$AH_BUCKET/secrets/$key - 2>/dev/null) || continue
    echo "${key}=$val"
  done
